name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk/?ref=release/1.12.0&depth=1
parameters:
  - name: internet-accessible
    value: true
---
name: buckets
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/buckets/?ref=release/1.12.0&depth=1
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-policy
    value: DESTROY