name: Snyk

on:
  workflow_dispatch:

  schedule:
    - cron: "0 9 * * 1"  # runs each Monday at 9:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install uv
        run: pip install uv
      - name: Create requirements.txt
        run: uv pip compile pyproject.toml -o requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Create and activate venv
        run: |
          uv venv -p 3.12 --seed
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          source .venv/bin/activate
          uv pip install -r requirements.txt
      - name: Snyk scan with venv
        id: snyk
        run: |
          npm install -g snyk
          snyk test --severity-threshold=medium --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif
      - name: Notify Slack on Failure
        if: steps.snyk.outcome == 'failure'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"repository\": \"${{ github.repository }}\",
            \"branch\": \"${{ github.ref_name }}\",
            \"actor\": \"${{ github.actor }}\",
            \"run_url\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
