name: Snyk

on:
  workflow_dispatch:

  schedule:
    - cron: "0 9 * * 1"  # runs each Monday at 9:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Install uv
        run: pip install uv
      - name: Create requirements.txt
        run: uv pip compile pyproject.toml -o requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create and activate venv
        run: |
          uv venv -p 3.12 --seed
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          source .venv/bin/activate
          uv pip install -r requirements.txt
      - name: Snyk scan with venv
        run: |
          source .venv/bin/activate
          uv pip install pysnyk
          snyk test --severity-threshold=medium --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif
